import pandas as pd

def clean_dataset(file_path):
    # 1. Load dataset
    df = pd.read_csv(file_path)

    # 2. Standardize column names
    df.columns = df.columns.str.strip().str.replace(" ", "_")

    # 3. Remove duplicate rows
    df = df.drop_duplicates()

    # 4. Normalize all text columns
    text_columns = [
        "Transaction_ID",
        "Day",
        "Time",
        "Type_of_Food",
        "Food_Category",
        "Payment_Method",
        "Customer_Type"
    ]
    for col in text_columns:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.lower().str.capitalize()

    # 5. Drop rows with missing Transaction_ID
    if "Transaction_ID" in df.columns:
        df = df[df["Transaction_ID"].str.strip() != ""]

    # 6. Rename Type_of_Food → Food_Item
    if "Type_of_Food" in df.columns:
        df = df.rename(columns={"Type_of_Food": "Food_Item"})

    # 7. Fix known Food_Item typos
    if "Food_Item" in df.columns:
        df["Food_Item"] = df["Food_Item"].replace({
            "Fewa burger": "Fewa Burger",
            "Siomai rice": "Siomai Rice",
            "Sisig": "Sisig",
            "Squash based churros": "Squash-Based Churros"
        })

    # 8. Standardize Payment_Method (including E-Wallet)
    if "Payment_Method" in df.columns:
        df["Payment_Method"] = df["Payment_Method"].replace({
            "Gcash": "GCash",
            "Cash": "Cash",
            "Maya": "Maya",
            "E-wallet": "E-Wallet"
        })
        df["Payment_Method"] = df["Payment_Method"].replace("nan", pd.NA)
        df["Payment_Method"] = df["Payment_Method"].fillna("Unknown")

    # 9. Standardize Date format
    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.strftime("%Y-%m-%d")

    # 10. Standardize Time format (HH:MM)
    if "Time" in df.columns:
        df["Time"] = pd.to_datetime(df["Time"], errors="coerce").dt.strftime("%H:%M")

    # 11. Convert numeric columns
    number_columns = [
        "Stall_Number",
        "Quantity_Sold",
        "Unit_Price",
        "Total_Sales",
        "Stock_Before",
        "Stock_After"
    ]
    for col in number_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 12. Restrict Stall_Number to valid stalls (1–27 only)
    valid_stalls = list(range(1, 28))
    if "Stall_Number" in df.columns:
        df = df[df["Stall_Number"].isin(valid_stalls)]

    # 13. Remove invalid rows
    df = df[df["Quantity_Sold"] > 0]
    df = df[df["Unit_Price"] > 0]

    # 14. Enforce consistent Unit_Price per Food_Item (simple map)
    fixed_prices = {
        "Chicken Poppers": 65,
        "Siomai Rice": 65,
        "Fewa Burger": 35,
        "Sisig": 65,
        "Iced Coffee": 30,
        "Squash-Based Churros 4pcs": 49,
        "Squash-Based Churros 8pcs": 89,
        "Carrot-Based Churros 4pcs": 49,
        "Carrot-Based Churros 8pcs": 89,
        "Assorted Churros 4pcs": 49,
        "Assorted Churros 8pcs": 49,
        "Chocolate/Banana Dip": 15,
        "Extra Dip":10,
        "Veggie Chips Classic Crunch": 30,
        "Veggie Chips Classic Crunch W/Dip": 35,
        "Veggie Chips Sour Cream Crunch": 35,
        "Veggie Chips BBQ Crunch": 35,
        "Sparkly Drinks Mango Spark 16oz": 40,
        "Sparkly Drinks Mango Spark 22oz": 45,
        "Sparkly Drinks Cucumber Spark 16oz": 40,
        "Sparkly Drinks Cucumber Spark 22oz": 45,
        "Mango Spark 16oz + Crunch Chips ": 65,
        "Mango Spark 22oz + Crunch Chips ": 85,
        "Cucumber Spark 16oz + Crunch Chips ": 65,
        "Cucumber Spark 22oz + Crunch Chips ": 85,
        "Ice Lolly": 15,
        "Dessert Bar": 22,
        "Fiesta ICS": 30,
        "Gusto Ko 2": 20,
        "Sundae Cup": 18,
        "Classic Crunchy Bar": 25,
        "Premium Buko Salad": 30,
        "Creamstick": 28,
        "Premium Crunch Bar": 35,
        "Megastick": 35,
        "Hernz 850ml": 150,
        "Kape Vanilla": 38,
        "Kape Chocolate": 38,
        "Kape Caramel": 38,
        "Kape Hazelnut": 38,
        "Kape Latte": 43,
        "Kape Matcha": 48,
        "Flavored Fries Regular": 41,
        "Flavored Fries Large": 67,
        "Flavored Fries Jumbo": 97,
        "Flavored Fries Mega": 127,
        "Flavored Fries Giga": 198,
        "Flavored Fries Tera": 228,
        "Crunchy Chicken Pops Solo": 75,
        "Crunchy Chicken Pops Large": 95,
        "Crunchy Chicken Pops Mega": 199,
        "Loopys Large": 75,
        "Loopys Mega": 135,
        "Mix & Match Large Mix": 99,
        "Mix & Match Mega Mix": 149,
        "Mix & Match Tera Mix": 259,
        "Bagnet w/ Rice": 70,
        "BBQ (Sticks) w/ Rice": 70,
        "Hotdog w/ Rice": 50,
        "Bagnet + BBQ w/ Rice": 80,
        "Grilled Hotdog + BBQ w/ Rice": 75,
        "Add On: Bagnet": 50,
        "Add On: BBQ": 25,
        "Add On: Hotdog": 30,
        "Naked Kare Kare Crispy Bagnet Solo": 99,
        "Naked Kare Kare Crispy Bagnet Big": 120,
        "Beef Samgyup Bowl": 99,
        "Chicken Pastil With Rice": 60,
        "Buy 1 Take 1 Beef Pepper Rice": 119,
        "Buy 1 Take 1 Shawarma Rice": 99,
        "Buy 1 Take 1 Pad Kra Prao": 119,
        "Chao Fan Toppings Meatballs": 70,
        "Chao Fan Toppings Shanghai": 70,
        "Chao Fan Toppings Hotdog": 70,
        "Chao Fan Toppings Longganisa": 70,
        "Chao Fan Toppings Embotido": 70,
        "Chao Fan Toppings Maling": 70,
        "Chao Fan Toppings Tofu Sisig": 80,
        "Chao Fan Toppings Burger Steak": 80,
        "Chao Fan Toppings Siomai": 80,
        "Lemonade Medium": 25,
        "Lemonade Large": 35,
        "Cucumber Medium": 25,
        "Cucumber Large": 35,
        "Watermelon Medium": 25,
        "Watermelon Large": 35,
        "Sisig Rice": 70,
        "Buy 1 Take 1 Burger": 30,
        "Belony w/ rice": 30,
        "Belony w/ rice w/ egg": 40,
        "Longanisa w/ rice": 30,
        "Longanisa w/ rice w/ egg": 40,
        "Spam w/ rice": 35,
        "Spam w/ rice w/ egg": 45,
        "Hungarian w/ rice": 35,
        "Hungarian w/ rice w/ egg": 45,
        "Ham w/ bread": 30,
        "Ham w/ bread w/ egg": 40,
        "Ham w/ bread w/ cheese": 50,
        "Egg w/ bread": 20,
        "Egg w/ bread w/ cheese": 30,
        "Juice Bar Lychee L": 25,
        "Juice Bar Lychee XL": 40,
        "Juice Bar Melon M": 20,
        "Juice Bar Melon L": 25,
        "Juice Bar Melon XL": 40,
        "Juice Bar Red Tea M": 20,
        "Juice Bar Red Tea L": 25,
        "Juice Bar Red Tea XL": 40,
        "Buy 1 Take 1 Hamburger": 45,
        "Buy 1 Take 1 Hamburger w/ cheese": 49,
        "FEWA Egg Sandwich": 30,
        "FEWA Egg Sandwich w/ Cheese": 35,
        "FEWA Ham Sandwich": 30,
        "FEWA Ham Sandwich w/ Cheese": 35,
        "Burgersilog": 60,
        "Burger Steak w/ Rice 1 Pc": 40,
        "Burger Steak w/ Rice 2 Pcs": 60,
        "Burger Patties w/ Gravy 1 Pc": 25,
        "Burger Patties w/ Gravy 2 Pcs": 50,
        "Hamsilog": 60,
        "Longsilog": 60,
        "Malingsilog": 60,
        "Hotsilog": 65,
        "Sisigsilog": 75,
        "Rice": 15,
        "Boiled Egg": 15,
        "Siomai 3 Pcs": 20,
        "Fried Rice w/ Egg": 40,
        "Siomai Silog": 55,
        "Fried Noodles w/ Siomai": 50,
        "Siomai Rice": 40,
        "Lemon Iced Tea Small": 20,
        "Lemon Iced Tea Medium": 35,
        "Lemon Iced Tea Large": 45,
        "Lemon Iced Tea 1L": 50,
        "Red Iced Tea Small": 20,
        "Red Iced Tea Medium": 35,
        "Red Iced Tea Large": 45,
        "Red Iced Tea 1L": 50,
        "Milky Watermelon Small": 25,
        "Milky Watermelon Medium": 35,
        "Milky Watermelon Large": 45,
        "Milky Watermelon 1L": 60,
        "Mango Tapioca Small": 25,
        "Mango Tapioca Medium": 35,
        "Mango Tapioca Large": 45,
        "Mango Tapioca 1L": 60,
        "Fruitmilk Mango S": 39,
        "Fruitmilk Mango M": 49,
        "Fruitmilk Mango L": 59,
        "Fruitmilk Blueberry S": 39,
        "Fruitmilk Blueberry M": 49,
        "Fruitmilk Blueberry L": 59,
        "Fruitmilk Strawberry S": 39,
        "Fruitmilk Strawberry M": 49,
        "Fruitmilk Strawberry L": 59,
        "Corndog": 30,
        "Corndog w/ Cheese": 35,
        "Lumpiang Toge": 25,
        "Dynamite": 25,
        "Cheese Sticks 8 Pcs": 25,
        "Tokwa 4 Pcs": 20,
        "Veggie Balls 5 Pcs": 20,
        "Fishballs 10 Pcs": 20,
        "Kikiam 10 Pcs": 25,
        "Squid Balls 4 Pcs": 20,
        "Kwek Kwek 4 Pcs": 25,
        "Tokneneng": 25,
        "Omelette With Rice Corn Beef": 55,
        "Omelette With Rice Tuna": 55,
        "Omelette With Rice Hotdog": 55,
        "Silog Meals Luncheon Meat": 55,
        "Silog Meals Skinless Longganisa": 55,
        "Silog Meals Burger Steak": 65,
        "Silog Meals Bacon": 60,
        "Silog Meals Sausage Bacon Wrap": 55,
        "Silog Meals Hotdog": 55,
        "Silog Meals Nuggets": 55,
        "Silog Meals Ham": 55,
        "Flavored Chicken Wings Meal Salted Egg": 75,
        "Flavored Chicken Wings Meal Sweet Chili": 75,
        "Flavored Chicken Wings Meal Garlic Parmesan": 75,
        "Flavored Chicken Wings Meal Salt & Pepper": 75,
        "Flavored Chicken Wings Meal Classic Buffalo": 75,
        "Flavored Chicken Wings Meal Honey Butter Glazed": 75,
        "Flavored Chicken Wings Meal Spicy Korean Barbecue": 75,
        "French Fries Cheese S": 35,
        "French Fries Cheese L": 60,
        "French Fries Barbecue S": 35,
        "French Fries Barbecue L": 60,
        "French Fries Sour And Cream S": 35,
        "French Fries Sour And Cream L": 60,
        "Hungarian Sausage With Rice Cheese": 69,
        "Hungarian Sausage With Rice Plain": 64,
        "Pancake": 35,
        "Pancit Canton": 30,
        "Hot Coffee": 15,
        "Garlic Wings": 70,
        "Teriyaki Wings": 70,
        "Bbq Wings": 70,
        "Garlic Parmesan Wings": 70,
        "Honey Butter Wings": 70,
        "Salted Egg Wings": 70,
        "Chicken Fillet": 60,
        "Bacon Hotdog Rice": 60,
        "Combo Hotdog Rice": 45,
        "Combo Hotdog On Stick": 30,
        "Cheesy Fewa": 65,
        "Cheesy Biggy Burger Solo": 40,
        "Cheesy Biggy Burger Buy 1 Take 1": 75,
        "Buy 1 Take 1": 40,
        "Cheesy Hotdog": 35,
        "Fresh Lemonade Small": 20,
        "Fresh Lemonade Medium": 25,
        "Fresh Lemonade Large": 35,
        "Add Ons Yakult": 15,
        "Add Ons Cocumber": 15,
        "Add Ons Strawberry": 15,
        "Belgian Chocolate": 30,
        "Hazelnut": 32,
        "Bacon & Cheese": 35,
        "Ultimate Ube": 26,
        "German Cheese Franks": 35,
        "Ricebowl Dumplings": 69,
        "Ricebowl Pork Siomai": 69,
        "Ricebowl Shanghai": 69,
        "Ricebowl Chicken Fillet": 79,
        "Shawarma Pita Solo": 49,
        "Shawarma Rice": 79,
        "Shawarma Pita Meal": 113,
        "Shawarma Rice Meal": 143,
        "Egg Mayo": 39,
        "Ham & Cheese": 39,
        "Ham & Egg": 39,
        "Tuna": 39,
        "Chicken": 39,
        "Egg Mayo Med. Lemonade Reg. Fries": 119,
        "Ham & Cheese Med. Lemonade Reg. Fries": 119,
        "Ham & Egg Med. Lemonade Reg. Fries": 119,
        "Tuna Med. Lemonade Reg. Fries": 119,
        "Chicken Med. Lemonade Reg. Fries": 119,
        "Fries Large": 55,
        "Squeeze Lemonade Classic Medium": 25,
        "Squeeze Lemonade Classic Large": 35,
        "Squeeze Lemonade w/ Water Melon Medium": 40,
        "Squeeze Lemonade w/ Water Melon Large": 50,
        "Squeeze Lemonade w/ Yakult Medium": 40,
        "Squeeze Lemonade w/ Yakult Large": 50,
        "Squeeze Lemonade w/ Cucumber Medium": 35,
        "Squeeze Lemonade w/ Cucumber Large": 45,
        "Siomai Rice": 40,
        "Fried Noodles w/ Siomai": 50,
        "Iced Coffee 16 oz": 30,
        "Iced Coffee 22 oz": 45,
        "Burger Steak w/ Rice 1 pc": 40,
        "Burger Steak w/ Rice 2 pcs": 60,
        "Delicious Rice Chicken Pops": 50,
        "Chicken Onion Rings Rice Bowl": 50,
        "Mix And Match": 75,
        "Jumbo Pork Siomai 3 Pcs With Rice": 50,
        "Jumbo Pork Siomai Each": 15,
        "Beef Tapa Rice Bowl": 50,
        "Cucumber Lemonade S": 20,
        "Cucumber Lemonade M": 30,
        "Cucumber Lemonade L": 40,
        "Lemon Iced Tea S": 20,
        "Lemon Iced Tea M": 30,
        "Lemon Iced Tea L": 40,
        "Hungarian w/ Rice": 65,
        "Jumbo Cheesedog w/ Rice": 50,
        "Burger Steak w/ Rice 1 pc": 40,
        "Burger Steak w/ Rice 2 pcs": 60,
        "Student Meal": 50,
        "Buy 1 Take 1 Purefoods Hotdog Sandwich": 49,
        "Buy 1 Take 1 Hamburger": 45,
        "Buy 1 Take 1 Hamburger w/ Cheese": 49,
        "Special Fewa": 70,
        "P1 1 pc Chicken w/ Rice & Drinks": 65,
        "P2 1 pc Chicken w/ Rice": 45,
        "C1 2 pcs Chicken w/ Rice & Drinks": 90,
        "C2 2 pcs Chicken w/ Rice": 70,
        "Rice": 10,
        "Rice Meals Siomai": 35,
        "Rice Meals Fish Fillet": 35,
        "Rice Meals Hotdog": 35,
        "Rice Meals Luncheon Meat": 35,
        "Rice Meals Burger Steak": 35,
        "Rice Meals Chicken Fillet": 50,
        "Rice Meals Hungarian Sausage": 60,
        "Rice Meals Pork Sisig": 60,
        "Rice Meals Lechon Paksiw": 60,
        "Add Chao Fan Rice Upgrade": 15,
        "Add Egg": 15,
        "C2 Apple S": 20,
        "C2 Apple M": 30,
        "C2 Apple L": 40,
        "Lemon Iced Tea S": 20,
        "Lemon Iced Tea M": 30,
        "Lemon Iced Tea L": 40,
        "Lemonade S": 20,
        "Lemonade M": 30,
        "Lemonade L": 40,
        "Chocolate S": 20,
        "Chocolate M": 30,
        "Chocolate L": 40,
        "Sago't Gulaman S": 20,
        "Sago't Gulaman M": 30,
        "Sago't Gulaman L": 40,
        "Rice Bowl Boneless Fried Chicken": 65,
        "Add Spicy Flavor": 5,
        "Chicken Wings D1 2 Pcs With Rice": 75,
        "Chicken Wings D2 4 Pcs With Rice": 139,
        "Ala-Carte 6 Pcs": 205,
        "Ala-Carte 8 Pcs": 270,
        "Ala-Carte 12 Pcs": 408,
        "Add Dips": 10,
        "Drinks 16 Oz": 25,
        "Drinks 22 Oz": 35,
        "To-Go Party 20 Pcs": 680,
        "To-Go Party 30 Pcs": 1025,
        "To-Go Party 50 Pcs": 1710,
        "Coffee Latte 16 oz": 39,
        "Coffee Latte 22 oz": 49,
        "Coffee Caramel Macchiato 16 oz": 39,
        "Coffee Caramel Macchiato 22 oz": 49,
        "Coffee White Chocolate 16 oz": 39,
        "Coffee White Chocolate 22 oz": 49,
        "Coffee Hazelnut Brew 16 oz": 39,
        "Coffee Hazelnut Brew 22 oz": 49,
        "Coffee Butterscotch 16 oz": 39,
        "Coffee Butterscotch 22 oz": 49,
        "Coffee Almond 16 oz": 39,
        "Coffee Almond 22 oz": 49,
        "Latte Series Spanish Latte 16 oz": 49,
        "Latte Series Spanish Latte 22 oz": 59,
        "Latte Series Matcha Latte 16 oz": 49,
        "Latte Series Matcha Latte 22 oz": 59,
        "Latte Series Choco Latte 16 oz": 49,
        "Latte Series Choco Latte 22 oz": 59,
        "Latte Series Strawberry Latte 16 oz": 49,
        "Latte Series Strawberry Latte 22 oz": 59,
        "Latte Series Blueberry Latte 16 oz": 49,
        "Latte Series Blueberry Latte 22 oz": 59,
        "Milktea Wintermelon 16 oz": 39,
        "Milktea Wintermelon 22 oz": 49,
        "Milktea Brown Sugar 16 oz": 39,
        "Milktea Brown Sugar 22 oz": 49,
        "Milktea Matcha 16 oz": 39,
        "Milktea Matcha 22 oz": 49,
        "Milktea Okinawa 16 oz": 39,
        "Milktea Okinawa 22 oz": 49,
        "Milktea Hokkaido 16 oz": 39,
        "Milktea Hokkaido 22 oz": 49,
        "Fruit Series Tea Lychee 16 oz": 39,
        "Fruit Series Tea Lychee 22 oz": 49,
        "Fruit Series Soda Lychee 16 oz": 49,
        "Fruit Series Soda Lychee 22 oz": 59,
        "Fruit Series Tea Strawberry 16 oz": 39,
        "Fruit Series Tea Strawberry 22 oz": 49,
        "Fruit Series Soda Strawberry 16 oz": 49,
        "Fruit Series Soda Strawberry 22 oz": 59,
        "Fruit Series Tea Green Apple 16 oz": 39,
        "Fruit Series Tea Green Apple 22 oz": 49,
        "Fruit Series Soda Green Apple 16 oz": 49,
        "Fruit Series Soda Green Apple 22 oz": 59,
        "Fruit Series Tea Passion Fruit 16 oz": 39,
        "Fruit Series Tea Passion Fruit 22 oz": 49,
        "Fruit Series Soda Passion Fruit 16 oz": 49,
        "Fruit Series Soda Passion Fruit 22 oz": 59,
        "Fruit Series Tea Blueberry 16 oz": 39,
        "Fruit Series Tea Blueberry 22 oz": 49,
        "Fruit Series Soda Blueberry 16 oz": 49,
        "Fruit Series Soda Blueberry 22 oz": 59,
        "Frappe Choco Java Chips 16 oz": 59,
        "Frappe Cheesecake 16 oz": 59,
        "Frappe Cookies & Cream 16 oz": 59,
        "Frappe Matcha 16 oz": 59,
        "Add-Ons Espresso": 10,
        "Add-Ons Fruit Jelly": 10,
        "Add-Ons Coffee Jelly": 10,
        "Add-Ons Tapioca Pearl": 10,
        "Mogu Series 16 oz": 39,
        "Mogu Series 22 oz": 49,
        "Special Halo-Halo": 50,
        "Banana Con Yelo Medium": 25,
        "Banana Con Yelo Large": 35,
        "Mais Con Yelo Medium": 25,
        "Mais Con Yelo Large": 35,
        "Add Leche Flan": 10,
        "Add Ube": 10,
        "Green Apple Soda with Rainbow Jelly S": 20,
        "Green Apple Soda with Rainbow Jelly M": 25,
        "Green Apple Soda with Rainbow Jelly L": 40,
        "Milo Cream-O S": 20,
        "Milo Cream-O M": 25,
        "Milo Cream-O L": 40,
        "C2 Apple S": 20,
        "C2 Apple M": 25,
        "Mango Tapioca M": 25,
        "Mango Tapioca L": 30,
        "Cucumber Lemonade S": 20,
        "Cucumber Lemonade M": 25,
        "Cucumber Lemonade L": 40,
        "Pork Mushroom w/ Rice": 75,
        "Boneless Chicken w/ Rice": 65,
        "Carbonara": 40,
        "Chicken Cordon": 65,
        "Bopis w/ Rice": 70,
        "Boneless Chicken Garlic Cheese Spicy w/ Rice": 65,
        "Ex's Burger": 110,
        "Campus Crush Burger": 110,
        "Dean's Burger": 95,
        "Terror Prof Burger": 85,
        "Quarter Pounder Burger": 65,
        "Lucky Day Le Minerale": 25,
        "Minute Maid": 19,
        "Minute Maid": 19,
        "Coke Red Coke Zero Royal Sprite": 40,
        "Quarter Pounder Steak Rice Meal": 100,
        "Gyudon Solo": 55,
        "Gyudon With Rice": 65,
        "Kare-Kare With Rice": 80,
        "Giant Chix Fillet Chiknchops": 75,
        "Mais Con Yelo": 40,
        "Saging Con Yelo": 35,
    }
    if "Food_Item" in df.columns and "Unit_Price" in df.columns:
        df["Unit_Price"] = df["Food_Item"].map(fixed_prices).fillna(df["Unit_Price"])

    # 15. Food_Category mapping
    category_map = {
        "Fewa Burger": "Snack",
        "Siomai Rice": "Meal",
        "Sisig": "Meal",
        "Veggie Balls": "Street Food"
    }
    if "Food_Item" in df.columns and "Food_Category" in df.columns:
        df["Food_Category"] = df["Food_Item"].map(category_map).fillna(df["Food_Category"])

    # 16. Clean Customer_Type (remove)
    if "Customer_Type" in df.columns:
        df["Customer_Type"] = df["Customer_Type"].str.strip()

    # 17. Handle missing values in Stock_Before / Stock_After
    for col in ["Stock_Before", "Stock_After"]:
        if col in df.columns:
            df[col] = df[col].fillna(0)  # or drop rows if preferred

    # 18. Recalculate Total_Sales
    df["Total_Sales"] = df["Quantity_Sold"] * df["Unit_Price"]

    # 19. Save cleaned dataset
    df.to_csv("data/lagoon_sales_cleaned.csv", index=False)

    return df