import pandas as pd

def clean_dataset(file_path):
    # 1. Load dataset
    df = pd.read_csv(file_path)

    # 2. Standardize column names
    df.columns = df.columns.str.strip().str.replace(" ", "_")

    # 3. Remove duplicate rows
    df = df.drop_duplicates()

    # 4. Normalize all text columns
    text_columns = [
        "Transaction_ID",
        "Day",
        "Time",
        "Type_of_Food",
        "Food_Category",
        "Payment_Method",
        "Customer_Type"
    ]
    for col in text_columns:
        if col in df.columns:
            df[col] = df[col].astype(str).str.strip().str.lower().str.capitalize()

    # 5. Drop rows with missing Transaction_ID
    if "Transaction_ID" in df.columns:
        df = df[df["Transaction_ID"].str.strip() != ""]

    # 6. Define the standard unit price for each food item
    fixed_prices = {
        "Chicken poppers": 65,
        "Siomai rice": 40,
        "Fewa burger": 35,
        "Sisig": 65,
        "Iced coffee": 30,
        "Squash-based churros 4pcs": 49,
        "Squash-based churros 8pcs": 89,
        "Carrot-based churros 4pcs": 49,
        "Carrot-based churros 8pcs": 89,
        "Assorted churros 4pcs": 49,
        "Assorted churros 8pcs": 49,
        "Chocolate/banana dip": 15,
        "Extra dip": 10,
        "Veggie chips classic crunch": 30,
        "Veggie chips classic crunch w/dip": 35,
        "Veggie chips sour cream crunch": 35,
        "Veggie chips bbq crunch": 35,
        "Sparkly drinks mango spark 16oz": 40,
        "Sparkly drinks mango spark 22oz": 45,
        "Sparkly drinks cucumber spark 16oz": 40,
        "Sparkly drinks cucumber spark 22oz": 45,
        "Mango spark 16oz + crunch chips ": 65,
        "Mango spark 22oz + crunch chips ": 85,
        "Cucumber spark 16oz + crunch chips ": 65,
        "Cucumber spark 22oz + crunch chips ": 85,
        "Ice lolly": 15,
        "Dessert bar": 22,
        "Fiesta ics": 30,
        "Gusto ko 2": 20,
        "Sundae cup": 18,
        "Classic crunchy bar": 25,
        "Premium buko salad": 30,
        "Creamstick": 28,
        "Premium crunch bar": 35,
        "Megastick": 35,
        "Hernz 850ml": 150,
        "Kape vanilla": 38,
        "Kape chocolate": 38,
        "Kape caramel": 38,
        "Kape hazelnut": 38,
        "Kape latte": 43,
        "Kape matcha": 48,
        "Flavored fries regular": 41,
        "Flavored fries large": 67,
        "Flavored fries jumbo": 97,
        "Flavored fries mega": 127,
        "Flavored fries giga": 198,
        "Flavored fries tera": 228,
        "Crunchy chicken pops solo": 75,
        "Crunchy chicken pops large": 95,
        "Crunchy chicken pops mega": 199,
        "Loopys large": 75,
        "Loopys mega": 135,
        "Mix & match large mix": 99,
        "Mix & match mega mix": 149,
        "Mix & match tera mix": 259,
        "Bagnet w/ rice": 70,
        "Bbq (sticks) w/ rice": 70,
        "Hotdog w/ rice": 50,
        "Bagnet + bbq w/ rice": 80,
        "Grilled hotdog + bbq w/ rice": 75,
        "Add on: bagnet": 50,
        "Add on: bbq": 25,
        "Add on: hotdog": 30,
        "Naked kare kare crispy bagnet solo": 99,
        "Naked kare kare crispy bagnet big": 120,
        "Beef samgyup bowl": 99,
        "Chicken pastil with rice": 60,
        "Buy 1 take 1 beef pepper rice": 119,
        "Buy 1 take 1 shawarma rice": 99,
        "Buy 1 take 1 pad kra prao": 119,
        "Chao fan toppings meatballs": 70,
        "Chao fan toppings shanghai": 70,
        "Chao fan toppings hotdog": 70,
        "Chao fan toppings longganisa": 70,
        "Chao fan toppings embotido": 70,
        "Chao fan toppings maling": 70,
        "Chao fan toppings tofu sisig": 80,
        "Chao fan toppings burger steak": 80,
        "Chao fan toppings siomai": 80,
        "Lemonade medium": 25,
        "Lemonade large": 35,
        "Cucumber medium": 25,
        "Cucumber large": 35,
        "Watermelon medium": 25,
        "Watermelon large": 35,
        "Sisig rice": 70,
        "Buy 1 take 1 burger": 30,
        "Belony w/ rice": 30,
        "Belony w/ rice w/ egg": 40,
        "Longanisa w/ rice": 30,
        "Longanisa w/ rice w/ egg": 40,
        "Spam w/ rice": 35,
        "Spam w/ rice w/ egg": 45,
        "Hungarian w/ rice": 65,
        "Hungarian w/ rice w/ egg": 45,
        "Ham w/ bread": 30,
        "Ham w/ bread w/ egg": 40,
        "Ham w/ bread w/ cheese": 50,
        "Egg w/ bread": 20,
        "Egg w/ bread w/ cheese": 30,
        "Juice bar lychee l": 25,
        "Juice bar lychee xl": 40,
        "Juice bar melon m": 20,
        "Juice bar melon l": 25,
        "Juice bar melon xl": 40,
        "Juice bar red tea m": 20,
        "Juice bar red tea l": 25,
        "Juice bar red tea xl": 40,
        "Buy 1 take 1 hamburger": 45,
        "Buy 1 take 1 hamburger w/ cheese": 49,
        "Fewa egg sandwich": 30,
        "Fewa egg sandwich w/ cheese": 35,
        "Fewa ham sandwich": 30,
        "Fewa ham sandwich w/ cheese": 35,
        "Burgersilog": 60,
        "Burger steak w/ rice 1 pc": 40,
        "Burger steak w/ rice 2 pcs": 60,
        "Burger patties w/ gravy 1 pc": 25,
        "Burger patties w/ gravy 2 pcs": 50,
        "Hamsilog": 60,
        "Longsilog": 60,
        "Malingsilog": 60,
        "Hotsilog": 65,
        "Sisigsilog": 75,
        "Rice": 15,
        "Boiled egg": 15,
        "Siomai 3 pcs": 20,
        "Fried rice w/ egg": 40,
        "Siomai silog": 55,
        "Fried noodles w/ siomai": 50,
        "Lemon iced tea small": 20,
        "Lemon iced tea medium": 35,
        "Lemon iced tea large": 45,
        "Lemon iced tea 1l": 50,
        "Red iced tea small": 20,
        "Red iced tea medium": 35,
        "Red iced tea large": 45,
        "Red iced tea 1l": 50,
        "Milky watermelon small": 25,
        "Milky watermelon medium": 35,
        "Milky watermelon large": 45,
        "Milky watermelon 1l": 60,
        "Mango tapioca small": 25,
        "Mango tapioca medium": 35,
        "Mango tapioca large": 45,
        "Mango tapioca 1l": 60,
        "Fruitmilk mango s": 39,
        "Fruitmilk mango m": 49,
        "Fruitmilk mango l": 59,
        "Fruitmilk blueberry s": 39,
        "Fruitmilk blueberry m": 49,
        "Fruitmilk blueberry l": 59,
        "Fruitmilk strawberry s": 39,
        "Fruitmilk strawberry m": 49,
        "Fruitmilk strawberry l": 59,
        "Corndog": 30,
        "Corndog w/ cheese": 35,
        "Lumpiang toge": 25,
        "Dynamite": 25,
        "Cheese sticks 8 pcs": 25,
        "Tokwa 4 pcs": 20,
        "Veggie balls 5 pcs": 20,
        "Fishballs 10 pcs": 20,
        "Kikiam 10 pcs": 25,
        "Squid balls 4 pcs": 20,
        "Kwek kwek 4 pcs": 25,
        "Tokneneng": 25,
        "Omelette with rice corn beef": 55,
        "Omelette with rice tuna": 55,
        "Omelette with rice hotdog": 55,
        "Silog meals luncheon meat": 55,
        "Silog meals skinless longganisa": 55,
        "Silog meals burger steak": 65,
        "Silog meals bacon": 60,
        "Silog meals sausage bacon wrap": 55,
        "Silog meals hotdog": 55,
        "Silog meals nuggets": 55,
        "Silog meals ham": 55,
        "Flavored chicken wings meal salted egg": 75,
        "Flavored chicken wings meal sweet chili": 75,
        "Flavored chicken wings meal garlic parmesan": 75,
        "Flavored chicken wings meal salt & pepper": 75,
        "Flavored chicken wings meal classic buffalo": 75,
        "Flavored chicken wings meal honey butter glazed": 75,
        "Flavored chicken wings meal spicy korean barbecue": 75,
        "French fries cheese s": 35,
        "French fries cheese l": 60,
        "French fries barbecue s": 35,
        "French fries barbecue l": 60,
        "French fries sour and cream s": 35,
        "French fries sour and cream l": 60,
        "Hungarian sausage with rice cheese": 69,
        "Hungarian sausage with rice plain": 64,
        "Pancake": 35,
        "Pancit canton": 30,
        "Hot coffee": 15,
        "Garlic wings": 70,
        "Teriyaki wings": 70,
        "Bbq wings": 70,
        "Garlic parmesan wings": 70,
        "Honey butter wings": 70,
        "Salted egg wings": 70,
        "Chicken fillet": 60,
        "Bacon hotdog rice": 60,
        "Combo hotdog rice": 45,
        "Combo hotdog on stick": 30,
        "Cheesy fewa": 65,
        "Cheesy biggy burger solo": 40,
        "Cheesy biggy burger buy 1 take 1": 75,
        "Buy 1 take 1": 40,
        "Cheesy hotdog": 35,
        "Fresh lemonade small": 20,
        "Fresh lemonade medium": 25,
        "Fresh lemonade large": 35,
        "Add ons yakult": 15,
        "Add ons cocumber": 15,
        "Add ons strawberry": 15,
        "Belgian chocolate": 30,
        "Hazelnut": 32,
        "Bacon & cheese": 35,
        "Ultimate ube": 26,
        "German cheese franks": 35,
        "Ricebowl dumplings": 69,
        "Ricebowl pork siomai": 69,
        "Ricebowl shanghai": 69,
        "Ricebowl chicken fillet": 79,
        "Shawarma pita solo": 49,
        "Shawarma rice": 79,
        "Shawarma pita meal": 113,
        "Shawarma rice meal": 143,
        "Egg mayo": 39,
        "Ham & cheese": 39,
        "Ham & egg": 39,
        "Tuna": 39,
        "Chicken": 39,
        "Egg mayo med. lemonade reg. fries": 119,
        "Ham & cheese med. lemonade reg. fries": 119,
        "Ham & egg med. lemonade reg. fries": 119,
        "Tuna med. lemonade reg. fries": 119,
        "Chicken med. lemonade reg. fries": 119,
        "Fries large": 55,
        "Squeeze lemonade classic medium": 25,
        "Squeeze lemonade classic large": 35,
        "Squeeze lemonade w/ water melon medium": 40,
        "Squeeze lemonade w/ water melon large": 50,
        "Squeeze lemonade w/ yakult medium": 40,
        "Squeeze lemonade w/ yakult large": 50,
        "Squeeze lemonade w/ cucumber medium": 35,
        "Squeeze lemonade w/ cucumber large": 45,
        "Iced coffee 16 oz": 30,
        "Iced coffee 22 oz": 45,
        "Delicious rice chicken pops": 50,
        "Chicken onion rings rice bowl": 50,
        "Mix and match": 75,
        "Jumbo pork siomai 3 pcs with rice": 50,
        "Jumbo pork siomai each": 15,
        "Beef tapa rice bowl": 50,
        "Cucumber lemonade s": 20,
        "Cucumber lemonade m": 30,
        "Cucumber lemonade l": 40,
        "Lemon iced tea s": 20,
        "Lemon iced tea m": 30,
        "Lemon iced tea l": 40,
        "Jumbo cheesedog w/ rice": 50,
        "Student meal": 50,
        "Buy 1 take 1 purefoods hotdog sandwich": 49,
        "Special fewa": 70,
        "P1 1 pc chicken w/ rice & drinks": 65,
        "P2 1 pc chicken w/ rice": 45,
        "C1 2 pcs chicken w/ rice & drinks": 90,
        "C2 2 pcs chicken w/ rice": 70,
        "Rice meals siomai": 35,
        "Rice meals fish fillet": 35,
        "Rice meals hotdog": 35,
        "Rice meals luncheon meat": 35,
        "Rice meals burger steak": 35,
        "Rice meals chicken fillet": 50,
        "Rice meals hungarian sausage": 60,
        "Rice meals pork sisig": 60,
        "Rice meals lechon paksiw": 60,
        "Add chao fan rice upgrade": 15,
        "Add egg": 15,
        "C2 apple s": 20,
        "C2 apple m": 30,
        "C2 apple l": 40,
        "Lemonade s": 20,
        "Lemonade m": 30,
        "Lemonade l": 40,
        "Chocolate s": 20,
        "Chocolate m": 30,
        "Chocolate l": 40,
        "Sago't gulaman s": 20,
        "Sago't gulaman m": 30,
        "Sago't gulaman l": 40,
        "Rice bowl boneless fried chicken": 65,
        "Add spicy flavor": 5,
        "Chicken wings d1 2 pcs with rice": 75,
        "Chicken wings d2 4 pcs with rice": 139,
        "Ala-carte 6 pcs": 205,
        "Ala-carte 8 pcs": 270,
        "Ala-carte 12 pcs": 408,
        "Add dips": 10,
        "Drinks 16 oz": 25,
        "Drinks 22 oz": 35,
        "To-go party 20 pcs": 680,
        "To-go party 30 pcs": 1025,
        "To-go party 50 pcs": 1710,
        "Coffee latte 16 oz": 39,
        "Coffee latte 22 oz": 49,
        "Coffee caramel macchiato 16 oz": 39,
        "Coffee caramel macchiato 22 oz": 49,
        "Coffee white chocolate 16 oz": 39,
        "Coffee white chocolate 22 oz": 49,
        "Coffee hazelnut brew 16 oz": 39,
        "Coffee hazelnut brew 22 oz": 49,
        "Coffee butterscotch 16 oz": 39,
        "Coffee butterscotch 22 oz": 49,
        "Coffee almond 16 oz": 39,
        "Coffee almond 22 oz": 49,
        "Latte series spanish latte 16 oz": 49,
        "Latte series spanish latte 22 oz": 59,
        "Latte series matcha latte 16 oz": 49,
        "Latte series matcha latte 22 oz": 59,
        "Latte series choco latte 16 oz": 49,
        "Latte series choco latte 22 oz": 59,
        "Latte series strawberry latte 16 oz": 49,
        "Latte series strawberry latte 22 oz": 59,
        "Latte series blueberry latte 16 oz": 49,
        "Latte series blueberry latte 22 oz": 59,
        "Milktea wintermelon 16 oz": 39,
        "Milktea wintermelon 22 oz": 49,
        "Milktea brown sugar 16 oz": 39,
        "Milktea brown sugar 22 oz": 49,
        "Milktea matcha 16 oz": 39,
        "Milktea matcha 22 oz": 49,
        "Milktea okinawa 16 oz": 39,
        "Milktea okinawa 22 oz": 49,
        "Milktea hokkaido 16 oz": 39,
        "Milktea hokkaido 22 oz": 49,
        "Fruit series tea lychee 16 oz": 39,
        "Fruit series tea lychee 22 oz": 49,
        "Fruit series soda lychee 16 oz": 49,
        "Fruit series soda lychee 22 oz": 59,
        "Fruit series tea strawberry 16 oz": 39,
        "Fruit series tea strawberry 22 oz": 49,
        "Fruit series soda strawberry 16 oz": 49,
        "Fruit series soda strawberry 22 oz": 59,
        "Fruit series tea green apple 16 oz": 39,
        "Fruit series tea green apple 22 oz": 49,
        "Fruit series soda green apple 16 oz": 49,
        "Fruit series soda green apple 22 oz": 59,
        "Fruit series tea passion fruit 16 oz": 39,
        "Fruit series tea passion fruit 22 oz": 49,
        "Fruit series soda passion fruit 16 oz": 49,
        "Fruit series soda passion fruit 22 oz": 59,
        "Fruit series tea blueberry 16 oz": 39,
        "Fruit series tea blueberry 22 oz": 49,
        "Fruit series soda blueberry 16 oz": 49,
        "Fruit series soda blueberry 22 oz": 59,
        "Frappe choco java chips 16 oz": 59,
        "Frappe cheesecake 16 oz": 59,
        "Frappe cookies & cream 16 oz": 59,
        "Frappe matcha 16 oz": 59,
        "Add-ons espresso": 10,
        "Add-ons fruit jelly": 10,
        "Add-ons coffee jelly": 10,
        "Add-ons tapioca pearl": 10,
        "Mogu series 16 oz": 39,
        "Mogu series 22 oz": 49,
        "Special halo-halo": 50,
        "Banana con yelo medium": 25,
        "Banana con yelo large": 35,
        "Mais con yelo medium": 25,
        "Mais con yelo large": 35,
        "Add leche flan": 10,
        "Add ube": 10,
        "Green apple soda with rainbow jelly s": 20,
        "Green apple soda with rainbow jelly m": 25,
        "Green apple soda with rainbow jelly l": 40,
        "Milo cream-o s": 20,
        "Milo cream-o m": 25,
        "Milo cream-o l": 40,
        "Mango tapioca m": 25,
        "Mango tapioca l": 30,
        "Pork mushroom w/ rice": 75,
        "Boneless chicken w/ rice": 65,
        "Carbonara": 40,
        "Chicken cordon": 65,
        "Bopis w/ rice": 70,
        "Boneless chicken garlic cheese spicy w/ rice": 65,
        "Ex's burger": 110,
        "Campus crush burger": 110,
        "Dean's burger": 95,
        "Terror prof burger": 85,
        "Quarter pounder burger": 65,
        "Lucky day le minerale": 25,
        "Minute maid": 19,
        "Coke red coke zero royal sprite": 40,
        "Quarter pounder steak rice meal": 100,
        "Gyudon solo": 55,
        "Gyudon with rice": 65,
        "Kare-kare with rice": 80,
        "Giant chix fillet chiknchops": 75,
        "Mais con yelo": 40,
        "Saging con yelo": 35,
    }

    if "Type_of_Food" in df.columns:
        df["Unit_Price"] = (
            df["Type_of_Food"]
            .map(fixed_prices)
            .fillna(df["Unit_Price"])
        )

        df["Type_of_Food"] = df["Type_of_Food"].str.title()

    #7. Standardize Payment_Method (including E-Wallet)
    if "Payment_Method" in df.columns:
        df["Payment_Method"] = (
            df["Payment_Method"]
            .str.strip()
            .str.lower()
            .map({
                "cash": "Cash",
                "e-wallet": "E-Wallet",
                "gcash": "GCash",
                "maya": "Maya"
            })
            .fillna("Unknown")
    )

    if "Transaction_ID" in df.columns:
        df = df.drop_duplicates(subset=["Transaction_ID"], keep="first")

    #8. Standardize Date format
    if "Date" in df.columns:
        df["Date"] = pd.to_datetime(df["Date"], errors="coerce").dt.strftime("%Y-%m-%d")

    #9. Standardize Time format (HH:MM)
    if "Time" in df.columns:
        df["Time"] = pd.to_datetime(df["Time"], errors="coerce").dt.strftime("%H:%M")

    #10. Convert numeric columns
    number_columns = [
        "Stall_Number",
        "Quantity_Sold",
        "Unit_Price",
        "Total_Sales",
        "Stock_Before",
        "Stock_After"
    ]
    for col in number_columns:
        if col in df.columns:
            df[col] = pd.to_numeric(df[col], errors="coerce")

    # 11. Restrict Stall_Number to valid stalls (1–27 only)
    valid_stalls = [s for s in range(1, 28) if s not in [4, 5, 7]]
    if "Stall_Number" in df.columns:
        df = df[df["Stall_Number"].isin(valid_stalls)]

    # 12. Remove invalid rows
    df = df[df["Quantity_Sold"] > 0]
    df = df[df["Unit_Price"] > 0]

    # 13. Ensure unit prices match the standard price list
    if "Type_of_Food" in df.columns and "Unit_Price" in df.columns:
        df["Unit_Price"] = (
            df["Type_of_Food"]
            .map(fixed_prices)
            .fillna(df["Unit_Price"])
        )

        df["Type_of_Food"] = df["Type_of_Food"].str.title()

    # 14. Clean Customer_Type (remove)
    if "Customer_Type" in df.columns:
        df["Customer_Type"] = df["Customer_Type"].str.strip()

    # 15. Replace missing stock values with 0
    for col in ["Stock_Before", "Stock_After"]:
        if col in df.columns:
            df[col] = df[col].fillna(0)  # drop rows

    # 16. Recalculate Total_Sales
    df["Total_Sales"] = df["Quantity_Sold"] * df["Unit_Price"]

    # 17. Save cleaned dataset
    df.to_csv("data/lagoon_sales_cleaned.csv", index=False)

    return df